apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dwh-code-review
type: Opaque
stringData:
  MSSQL_CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=sqlserver,1433;Database=YourDb;Trusted_Connection=yes;Encrypt=yes;TrustServerCertificate=yes;"
  LLM_API_KEY: ""
  API_ACCESS_TOKEN: ""
  API_ADMIN_TOKEN: ""
