{{- if .Values.backendSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dwh-code-review.backend.secretName" . }}
type: Opaque
stringData:
{{- range $k, $v := .Values.backendSecret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
